### ISSUE TITLE
miio-cli.php smart_night_light_on

### ISSUE THREAD

**Issue by BrownC0de** [skysilver-lab/php-miio#1]
С лампой все отлично, но появилась мысль добавить к домотиксу ночник этой ламы. Нашел параметр enable_bl, но как не пробовал, приходит ответ "ок" но ночник в ней не включается. Я что-то делаю не так?

**Comment by skysilver-lab** [comment]
А что за лампа-то? ))

**Comment by skysilver-lab** [comment]
Попробуй так
`{"id":1,"method":"set_bricct","params":[0,0]}`

**Comment by BrownC0de** [comment]
xiaomi philips ceiling.
Не,так не хочет {"result":["error"],"id":1}

**Comment by skysilver-lab** [comment]
Проверял при power = off?

Еще вариант попробовать через сцены:
{"id":1,"method":"apply_fixed_scene","params":[4]}
1-Яркий, 2-ТВ, 3-тёплый, 4-ночь

А что выдает команда {"id":1,"method":"miIO.info","params":[]} ?

**Comment by BrownC0de** [comment]
Все, понял, моя ошибка. И то и другое работает. Спасибо

**Comment by BrownC0de** [comment]
Я посколько от программирования далек, спрошу.
А как сделать баш скрипт, с проверкой состояния? Например, если после отправки на лампу команды пришел "ок" то скрипт прекращает работу, а если в течении грубо говоря 2 секунд ответ не пришел, или пришла ошибка - что бы команда повторилась?

**Comment by skysilver-lab** [comment]
В баше я вообще не понимаю, так что не смогу помочь с этим.
