### ISSUE TITLE
Добавление в composer

### ISSUE THREAD

**Issue by butschster** [skysilver-lab/php-miio#4]
Привет, а ты можешь закинуть на packagist в виде пакета?

**Comment by skysilver-lab** [comment]
Привет. Ниразу не имел с ним дела. Даже не представляю, как это делать. ))
Я вообщем то не планируют развивать эту библиотеку в текущем виде, т.к. сосредоточился над модулем для MajorDoMo. Там уже есть поддержка 16 девайсов.

**Comment by butschster** [comment]
Очень плохо. Я занимаюсь разработкой своей системы на php и не хотелось бы копировать весь код. Думал получить его в виде пакета.
