### ISSUE TITLE
mirobot clean zone

### ISSUE THREAD

**Issue by renat2985** [skysilver-lab/php-miio#5]
Спасибо большое за ваш трут!
Сделайте пожалуйста возможность просто отправлять команды на уборку нужной зоны.
Например:
```
$mirobot->zone(29500,21000,33200,25000,1)
```
В строчке указаны координаты зоны уборки и количество раз.
Буду очень рад за помощь, спасибо.

https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/app_zoned_clean.md

https://hackernoon.com/how-i-set-up-room-cleaning-automation-with-google-home-home-assistant-and-xiaomi-vacuum-cleaner-9149e0267e6d

**Comment by skysilver-lab** [comment]
Закину себе в задачи. Не знаю, когда получится.

А как на практике планируешь координаты вычислять? Пока что это сплошной геморой, как погляжу. )) Еще и карту пылик зачастую сбрасывает и начинает заново перестраивать.

**Comment by renat2985** [comment]
Спасибо буду ждать.

В целом там все достаточно просто с координатами, в том месте где он заряжается y = 25500, x = 25500.
Далее берем линейку, и например в лево (y) нужно уехать ему на 1м это будет 1000, то есть 25500 - 1000 получается y = 21500. Далее в верх от зарядки он должен уехать например на 2м это будет 2000 получается 25500 + 2000 получаем x= 28500 таким образом мы задали одну точку. По такой же аналогии задаем вторую. Я разметил 2 комнаты за 10 минут.

Возможно вам будет интересен еще 1 способ получения токена, он мне показался проще. Можно скачать MiHome сборку от vevs. Это тот же MiHome но на русском. 
В нем выбираем нужное устройство, нажимаем "Общие настройки" -> "Информация о сети" И там видим и IP и MAC и Токен.
Скачать apk можно тут: http://www.kapiba.ru/2017/11/mi-home.html
![screenshot_2018-03-17-14-09-29](https://user-images.githubusercontent.com/1230815/40391962-c3589e3a-5e22-11e8-8af7-2a68ba4f31e3.jpg)

**Comment by skysilver-lab** [comment]
Про сборку vevs, конечно, знаю. Фича с токенами в ней появилась только в марте 2018, а инструкции в данном репозитории писались в сентябре 2017 года. ))

Вообще, не думал, что кто-то пользуется данной либой. Я ее не развиваю, т.к. все силы брошены на модуль для MajorDoMo. Там сейчас вся движуха. )) И на форуме в последние дни тоже начали тему зональной уборки обсуждать. ))

**Comment by skysilver-lab** [comment]
Добавил.
`$mirobot->zoned_clean(29500,21000,33200,25000,1);`
