### ISSUE TITLE
token

### ISSUE THREAD

**Issue by gayratv** [skysilver-lab/php-miio#7]
Добрый день, огромное спасибо Вам за подробное описание протокола mio.

Я пробую взаимодействовать с mio первый раз.
Мне нужно считывать показания датчика температуры.

Исходя из Вашего руководства в первую очередь необходимо получить token для устройств.
Вы предложили 3 способа.

Попробовал все 3 - но как то безуспешно :)

Исходные данные:
Есть Xiaomi gateway выпуска 2018 года.
Подключил, привязал к Mi Home

Запустил php miio-cli.php --discover all
Почему то даже наличие gateway не найдено , не говоря о токене

Использовал метод 2, поставил adb, сделал архив, открыл базу miio2.db
gateway присутствует, другие устройства присутствуют, но token везде пустой.

Сбросил gateway (длительное нажатие на кнопку порядка 10 сек)
Подключился к его ap с компьютера , запустил php miio-cli.php --discover all - не найдено ни одного устройства.

Датчик температуры без gateway не прочитать .
Посоветуйте пожалуйста - что можно еще попробовать?

**Comment by skysilver-lab** [comment]
Эта библиотека не предназначена для работы с zigbee-устройствами через шлюз. Для них необходимо использовать API режима разработчика шлюза.

**Comment by gayratv** [comment]
Спасибо!

Можно ли как то получить token шлюза - или у него token нет ?
возможно моя проблема кроется в том что у меня MiHome свежий.
Вот тут сказано:
https://majordomo.smartliving.ru/forum/viewtopic.php?f=8&t=4677#p61208

что версия Mihome д.б. 5.0.29 и ниже.

**Comment by skysilver-lab** [comment]
Можно. Там как раз и написано крупным шрифтом:
простой способ получить токены - воспользоваться сборкой Mihome от vevs. (только для андроида)
Брать здесь http://www.kapiba.ru/2017/11/mi-home.html Если зайти в раздел "Информация о сети" нужного устройства, то увидим там заветный токен.
Либо можно в Михом зайти на страницу, на которой активировали режим разработчика шлюза. Там будут подробные сведения о шлюзе и токен в их числе.

**Comment by gayratv** [comment]
Спасибо!

Поставил MiHome версии 5.0.29 отсюда:
https://4pda.ru/forum/index.php?showtopic=661250&st=8180#Spoil-69071082-1

Tokens получил!!!!!
Ура!!!!!!!!
